name: Create backups

on:
  schedule:
    # CRON : mm hh jj MMM JJJ
    - cron: '40 12 * * *'
    
defaults:
  run:
    working-directory: ../

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: npm run backup
